<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 22.07.2011 09:27
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Defines supported fields for BrandMPN. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/BrandMPNType.html
 *
 */
class BrandMPNType extends EbatNs_ComplexType
{
	/**
	 * @var string
	 */
	protected $Brand;
	/**
	 * @var string
	 */
	protected $MPN;

	/**
	 * @return string
	 */
	function getBrand()
	{
		return $this->Brand;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setBrand($value)
	{
		$this->Brand = $value;
	}
	/**
	 * @return string
	 */
	function getMPN()
	{
		return $this->MPN;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setMPN($value)
	{
		$this->MPN = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('BrandMPNType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'Brand' =>
					array(
						'required' => false,
						'type' => 'string',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					),
					'MPN' =>
					array(
						'required' => false,
						'type' => 'string',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
