<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * This type is deprecated as the <b>GetProduct*</b> calls are no longer available. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/CharacteristicSetIDsType.html
 *
 */
class CharacteristicSetIDsType extends EbatNs_ComplexType
{
	/**
	 * @var string
	 */
	protected $ID;

	/**
	 * @return string
	 * @param integer $index 
	 */
	function getID($index = null)
	{
		if ($index !== null) {
			return $this->ID[$index];
		} else {
			return $this->ID;
		}
	}
	/**
	 * @return void
	 * @param string $value 
	 * @param  $index 
	 */
	function setID($value, $index = null)
	{
		if ($index !== null) {
			$this->ID[$index] = $value;
		} else {
			$this->ID = $value;
		}
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function addID($value)
	{
		$this->ID[] = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('CharacteristicSetIDsType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'ID' =>
					array(
						'required' => false,
						'type' => 'string',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => true,
						'cardinality' => '0..*'
					)
				));
	}
}
?>
