<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 22.07.2011 09:27
// $Id: $
// $Log: $
//
//
require_once 'PaginatedTransactionArrayType.php';
require_once 'AbstractResponseType.php';

/**
 * Response to GetItemsAwaitingFeedback. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GetItemsAwaitingFeedbackResponseType.html
 *
 */
class GetItemsAwaitingFeedbackResponseType extends AbstractResponseType
{
	/**
	 * @var PaginatedTransactionArrayType
	 */
	protected $ItemsAwaitingFeedback;

	/**
	 * @return PaginatedTransactionArrayType
	 */
	function getItemsAwaitingFeedback()
	{
		return $this->ItemsAwaitingFeedback;
	}
	/**
	 * @return void
	 * @param PaginatedTransactionArrayType $value 
	 */
	function setItemsAwaitingFeedback($value)
	{
		$this->ItemsAwaitingFeedback = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GetItemsAwaitingFeedbackResponseType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'ItemsAwaitingFeedback' =>
					array(
						'required' => false,
						'type' => 'PaginatedTransactionArrayType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
