<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 22.07.2011 09:27
// $Id: $
// $Log: $
//
//
require_once 'PictureManagerDetailsType.php';
require_once 'AbstractResponseType.php';

/**
 * Responds with information about content in a Picture Manager albumor the account 
 * settings. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GetPictureManagerDetailsResponseType.html
 *
 */
class GetPictureManagerDetailsResponseType extends AbstractResponseType
{
	/**
	 * @var PictureManagerDetailsType
	 */
	protected $PictureManagerDetails;

	/**
	 * @return PictureManagerDetailsType
	 */
	function getPictureManagerDetails()
	{
		return $this->PictureManagerDetails;
	}
	/**
	 * @return void
	 * @param PictureManagerDetailsType $value 
	 */
	function setPictureManagerDetails($value)
	{
		$this->PictureManagerDetails = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GetPictureManagerDetailsResponseType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'PictureManagerDetails' =>
					array(
						'required' => false,
						'type' => 'PictureManagerDetailsType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
