<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
//
require_once 'PromotionRuleArrayType.php';
require_once 'AbstractResponseType.php';

/**
 * Returns all promotion rules associated with the specified item or store 
 * category.Note:eBay Store Cross Promotions are no longer supported in the Trading 
 * API. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GetPromotionRulesResponseType.html
 *
 */
class GetPromotionRulesResponseType extends AbstractResponseType
{
	/**
	 * @var PromotionRuleArrayType
	 */
	protected $PromotionRuleArray;

	/**
	 * @return PromotionRuleArrayType
	 */
	function getPromotionRuleArray()
	{
		return $this->PromotionRuleArray;
	}
	/**
	 * @return void
	 * @param PromotionRuleArrayType $value 
	 */
	function setPromotionRuleArray($value)
	{
		$this->PromotionRuleArray = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GetPromotionRulesResponseType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'PromotionRuleArray' =>
					array(
						'required' => false,
						'type' => 'PromotionRuleArrayType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
