<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 22.07.2011 09:27
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';
require_once 'StoreType.php';

/**
 * Returns the data describing a seller's eBay store, including name, 
 * description,URL, and other information. The caller making the request must be 
 * the ownerof an eBay store. If the authenticated caller does not have an eBay 
 * store, theresponse is an error. A successful response contains either the 
 * complete storeconfiguration or information about the category hierarchy for the 
 * store only. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GetStoreResponseType.html
 *
 */
class GetStoreResponseType extends AbstractResponseType
{
	/**
	 * @var StoreType
	 */
	protected $Store;

	/**
	 * @return StoreType
	 */
	function getStore()
	{
		return $this->Store;
	}
	/**
	 * @return void
	 * @param StoreType $value 
	 */
	function setStore($value)
	{
		$this->Store = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GetStoreResponseType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'Store' =>
					array(
						'required' => false,
						'type' => 'StoreType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
