<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 22.07.2011 09:27
// $Id: $
// $Log: $
//
//
require_once 'SellingManagerEmailLogType.php';
require_once 'AbstractResponseType.php';

/**
 * Returns the log of emails not sent. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/GetSellingManagerEmailLogResponseType.html
 *
 */
class GetSellingManagerEmailLogResponseType extends AbstractResponseType
{
	/**
	 * @var SellingManagerEmailLogType
	 */
	protected $EmailLog;

	/**
	 * @return SellingManagerEmailLogType
	 * @param integer $index 
	 */
	function getEmailLog($index = null)
	{
		if ($index !== null) {
			return $this->EmailLog[$index];
		} else {
			return $this->EmailLog;
		}
	}
	/**
	 * @return void
	 * @param SellingManagerEmailLogType $value 
	 * @param  $index 
	 */
	function setEmailLog($value, $index = null)
	{
		if ($index !== null) {
			$this->EmailLog[$index] = $value;
		} else {
			$this->EmailLog = $value;
		}
	}
	/**
	 * @return void
	 * @param SellingManagerEmailLogType $value 
	 */
	function addEmailLog($value)
	{
		$this->EmailLog[] = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('GetSellingManagerEmailLogResponseType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'EmailLog' =>
					array(
						'required' => false,
						'type' => 'SellingManagerEmailLogType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => true,
						'cardinality' => '0..*'
					)
				));
	}
}
?>
