<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 22.07.2011 09:27
// $Id: $
// $Log: $
//
//
require_once 'ListingTipArrayType.php';
require_once 'EbatNs_ComplexType.php';

/**
 * Contains results returned from the Listing Analyzer recommendation engine. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ListingAnalyzerRecommendationsType.html
 *
 */
class ListingAnalyzerRecommendationsType extends EbatNs_ComplexType
{
	/**
	 * @var ListingTipArrayType
	 */
	protected $ListingTipArray;

	/**
	 * @return ListingTipArrayType
	 */
	function getListingTipArray()
	{
		return $this->ListingTipArray;
	}
	/**
	 * @return void
	 * @param ListingTipArrayType $value 
	 */
	function setListingTipArray($value)
	{
		$this->ListingTipArray = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ListingAnalyzerRecommendationsType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'ListingTipArray' =>
					array(
						'required' => false,
						'type' => 'ListingTipArrayType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
