<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
//
require_once 'MyMessagesAlertIDType.php';
require_once 'EbatNs_ComplexType.php';

/**
 * This type is deprecated because <b>MyMessagesAlert*</b> are deprecated. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/MyMessagesAlertIDArrayType.html
 *
 */
class MyMessagesAlertIDArrayType extends EbatNs_ComplexType
{
	/**
	 * @var MyMessagesAlertIDType
	 */
	protected $AlertID;

	/**
	 * @return MyMessagesAlertIDType
	 * @param integer $index 
	 */
	function getAlertID($index = null)
	{
		if ($index !== null) {
			return $this->AlertID[$index];
		} else {
			return $this->AlertID;
		}
	}
	/**
	 * @return void
	 * @param MyMessagesAlertIDType $value 
	 * @param  $index 
	 */
	function setAlertID($value, $index = null)
	{
		if ($index !== null) {
			$this->AlertID[$index] = $value;
		} else {
			$this->AlertID = $value;
		}
	}
	/**
	 * @return void
	 * @param MyMessagesAlertIDType $value 
	 */
	function addAlertID($value)
	{
		$this->AlertID[] = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('MyMessagesAlertIDArrayType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'AlertID' =>
					array(
						'required' => false,
						'type' => 'MyMessagesAlertIDType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => true,
						'cardinality' => '0..*'
					)
				));
	}
}
?>
