<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 22.07.2011 09:27
// $Id: $
// $Log: $
//
//
require_once 'OrderTransactionType.php';
require_once 'EbatNs_ComplexType.php';

/**
 * Contains a list of orders, transactions, or both, each of OrderTransactionType. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/OrderTransactionArrayType.html
 *
 */
class OrderTransactionArrayType extends EbatNs_ComplexType
{
	/**
	 * @var OrderTransactionType
	 */
	protected $OrderTransaction;

	/**
	 * @return OrderTransactionType
	 * @param integer $index 
	 */
	function getOrderTransaction($index = null)
	{
		if ($index !== null) {
			return $this->OrderTransaction[$index];
		} else {
			return $this->OrderTransaction;
		}
	}
	/**
	 * @return void
	 * @param OrderTransactionType $value 
	 * @param  $index 
	 */
	function setOrderTransaction($value, $index = null)
	{
		if ($index !== null) {
			$this->OrderTransaction[$index] = $value;
		} else {
			$this->OrderTransaction = $value;
		}
	}
	/**
	 * @return void
	 * @param OrderTransactionType $value 
	 */
	function addOrderTransaction($value)
	{
		$this->OrderTransaction[] = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('OrderTransactionArrayType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'OrderTransaction' =>
					array(
						'required' => false,
						'type' => 'OrderTransactionType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => true,
						'cardinality' => '0..*'
					)
				));
	}
}
?>
