<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * This type is deprecated as <b>GetProduct*</b> calls were deprecated. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ProductFinderConstraintType.html
 *
 */
class ProductFinderConstraintType extends EbatNs_ComplexType
{
	/**
	 * @var string
	 */
	protected $DisplayName;
	/**
	 * @var string
	 */
	protected $DisplayValue;

	/**
	 * @return string
	 */
	function getDisplayName()
	{
		return $this->DisplayName;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setDisplayName($value)
	{
		$this->DisplayName = $value;
	}
	/**
	 * @return string
	 */
	function getDisplayValue()
	{
		return $this->DisplayValue;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setDisplayValue($value)
	{
		$this->DisplayValue = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ProductFinderConstraintType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'DisplayName' =>
					array(
						'required' => false,
						'type' => 'string',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					),
					'DisplayValue' =>
					array(
						'required' => false,
						'type' => 'string',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
