<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Currently applies to tickets. May apply to other categories in the future. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/QuantityInfoType.html
 *
 */
class QuantityInfoType extends EbatNs_ComplexType
{
	/**
	 * @var int
	 */
	protected $MinimumRemnantSet;

	/**
	 * @return int
	 */
	function getMinimumRemnantSet()
	{
		return $this->MinimumRemnantSet;
	}
	/**
	 * @return void
	 * @param int $value 
	 */
	function setMinimumRemnantSet($value)
	{
		$this->MinimumRemnantSet = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('QuantityInfoType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'MinimumRemnantSet' =>
					array(
						'required' => false,
						'type' => 'int',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
