<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 22.07.2011 09:27
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Specifies how to return certain reminder types from the user's My eBay account. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ReminderCustomizationType.html
 *
 */
class ReminderCustomizationType extends EbatNs_ComplexType
{
	/**
	 * @var int
	 */
	protected $DurationInDays;
	/**
	 * @var boolean
	 */
	protected $Include;

	/**
	 * @return int
	 */
	function getDurationInDays()
	{
		return $this->DurationInDays;
	}
	/**
	 * @return void
	 * @param int $value 
	 */
	function setDurationInDays($value)
	{
		$this->DurationInDays = $value;
	}
	/**
	 * @return boolean
	 */
	function getInclude()
	{
		return $this->Include;
	}
	/**
	 * @return void
	 * @param boolean $value 
	 */
	function setInclude($value)
	{
		$this->Include = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ReminderCustomizationType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'DurationInDays' =>
					array(
						'required' => false,
						'type' => 'int',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					),
					'Include' =>
					array(
						'required' => false,
						'type' => 'boolean',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
