<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 22.07.2011 09:27
// $Id: $
// $Log: $
//
//
require_once 'BestOfferArrayType.php';
require_once 'AbstractResponseType.php';

/**
 * Contains a list of BestOffers that were either accepted or declined. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/RespondToBestOfferResponseType.html
 *
 */
class RespondToBestOfferResponseType extends AbstractResponseType
{
	/**
	 * @var BestOfferArrayType
	 */
	protected $RespondToBestOffer;

	/**
	 * @return BestOfferArrayType
	 */
	function getRespondToBestOffer()
	{
		return $this->RespondToBestOffer;
	}
	/**
	 * @return void
	 * @param BestOfferArrayType $value 
	 */
	function setRespondToBestOffer($value)
	{
		$this->RespondToBestOffer = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('RespondToBestOfferResponseType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'RespondToBestOffer' =>
					array(
						'required' => false,
						'type' => 'BestOfferArrayType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
