<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Type defining the <b>ReturnPolicyDetails.ReturnsWithin</b> container thatis 
 * returned in <b>GeteBayDetails</b>. This container contains the valuesthat may be 
 * used in the <b>ReturnPolicy.ReturnsWithinOption</b> field ofAdd/Revise/Relist 
 * API calls. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ReturnsWithinDetailsType.html
 *
 */
class ReturnsWithinDetailsType extends EbatNs_ComplexType
{
	/**
	 * @var token
	 */
	protected $ReturnsWithinOption;
	/**
	 * @var string
	 */
	protected $Description;

	/**
	 * @return token
	 */
	function getReturnsWithinOption()
	{
		return $this->ReturnsWithinOption;
	}
	/**
	 * @return void
	 * @param token $value 
	 */
	function setReturnsWithinOption($value)
	{
		$this->ReturnsWithinOption = $value;
	}
	/**
	 * @return string
	 */
	function getDescription()
	{
		return $this->Description;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setDescription($value)
	{
		$this->Description = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ReturnsWithinDetailsType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'ReturnsWithinOption' =>
					array(
						'required' => false,
						'type' => 'token',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					),
					'Description' =>
					array(
						'required' => false,
						'type' => 'string',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
