<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
//
require_once 'AbstractRequestType.php';

/**
 * Revokes a token before it would otherwise expire. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/RevokeTokenRequestType.html
 *
 */
class RevokeTokenRequestType extends AbstractRequestType
{
	/**
	 * @var boolean
	 */
	protected $UnsubscribeNotification;

	/**
	 * @return boolean
	 */
	function getUnsubscribeNotification()
	{
		return $this->UnsubscribeNotification;
	}
	/**
	 * @return void
	 * @param boolean $value 
	 */
	function setUnsubscribeNotification($value)
	{
		$this->UnsubscribeNotification = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('RevokeTokenRequestType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'UnsubscribeNotification' =>
					array(
						'required' => false,
						'type' => 'boolean',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
