<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 22.07.2011 09:27
// $Id: $
// $Log: $
//
//
require_once 'AbstractResponseType.php';

/**
 * Returns the status of save to template operation. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SaveItemToSellingManagerTemplateResponseType.html
 *
 */
class SaveItemToSellingManagerTemplateResponseType extends AbstractResponseType
{
	/**
	 * @var long
	 */
	protected $TemplateID;

	/**
	 * @return long
	 */
	function getTemplateID()
	{
		return $this->TemplateID;
	}
	/**
	 * @return void
	 * @param long $value 
	 */
	function setTemplateID($value)
	{
		$this->TemplateID = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SaveItemToSellingManagerTemplateResponseType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'TemplateID' =>
					array(
						'required' => false,
						'type' => 'long',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
