<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 22.07.2011 09:27
// $Id: $
// $Log: $
//
//
require_once 'StoreType.php';
require_once 'AbstractRequestType.php';

/**
 * Sets the configuration of the eBay store owned by the caller. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SetStoreRequestType.html
 *
 */
class SetStoreRequestType extends AbstractRequestType
{
	/**
	 * @var StoreType
	 */
	protected $Store;

	/**
	 * @return StoreType
	 */
	function getStore()
	{
		return $this->Store;
	}
	/**
	 * @return void
	 * @param StoreType $value 
	 */
	function setStore($value)
	{
		$this->Store = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SetStoreRequestType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'Store' =>
					array(
						'required' => false,
						'type' => 'StoreType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
