<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'LineItemType.php';

/**
 * This type provides information about one or more order line items in a Global 
 * Shipping Program package. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ShipmentLineItemType.html
 *
 */
class ShipmentLineItemType extends EbatNs_ComplexType
{
	/**
	 * @var LineItemType
	 */
	protected $LineItem;

	/**
	 * @return LineItemType
	 * @param integer $index 
	 */
	function getLineItem($index = null)
	{
		if ($index !== null) {
			return $this->LineItem[$index];
		} else {
			return $this->LineItem;
		}
	}
	/**
	 * @return void
	 * @param LineItemType $value 
	 * @param  $index 
	 */
	function setLineItem($value, $index = null)
	{
		if ($index !== null) {
			$this->LineItem[$index] = $value;
		} else {
			$this->LineItem = $value;
		}
	}
	/**
	 * @return void
	 * @param LineItemType $value 
	 */
	function addLineItem($value)
	{
		$this->LineItem[] = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ShipmentLineItemType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'LineItem' =>
					array(
						'required' => true,
						'type' => 'LineItemType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => true,
						'cardinality' => '1..*'
					)
				));
	}
}
?>
