<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 22.07.2011 09:27
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'SiteIDFilterCodeType.php';

/**
 * Contains the data that defines a site-based filter (used when searching for 
 * items and filtering the search result set). 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SiteLocationType.html
 *
 */
class SiteLocationType extends EbatNs_ComplexType
{
	/**
	 * @var SiteIDFilterCodeType
	 */
	protected $SiteID;

	/**
	 * @return SiteIDFilterCodeType
	 */
	function getSiteID()
	{
		return $this->SiteID;
	}
	/**
	 * @return void
	 * @param SiteIDFilterCodeType $value 
	 */
	function setSiteID($value)
	{
		$this->SiteID = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SiteLocationType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'SiteID' =>
					array(
						'required' => false,
						'type' => 'SiteIDFilterCodeType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
