<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 22.07.2011 09:27
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'StoreColorSchemeType.php';

/**
 * Set of eBay Store color schemes. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/StoreColorSchemeArrayType.html
 *
 */
class StoreColorSchemeArrayType extends EbatNs_ComplexType
{
	/**
	 * @var StoreColorSchemeType
	 */
	protected $ColorScheme;

	/**
	 * @return StoreColorSchemeType
	 * @param integer $index 
	 */
	function getColorScheme($index = null)
	{
		if ($index !== null) {
			return $this->ColorScheme[$index];
		} else {
			return $this->ColorScheme;
		}
	}
	/**
	 * @return void
	 * @param StoreColorSchemeType $value 
	 * @param  $index 
	 */
	function setColorScheme($value, $index = null)
	{
		if ($index !== null) {
			$this->ColorScheme[$index] = $value;
		} else {
			$this->ColorScheme = $value;
		}
	}
	/**
	 * @return void
	 * @param StoreColorSchemeType $value 
	 */
	function addColorScheme($value)
	{
		$this->ColorScheme[] = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('StoreColorSchemeArrayType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'ColorScheme' =>
					array(
						'required' => false,
						'type' => 'StoreColorSchemeType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => true,
						'cardinality' => '0..*'
					)
				));
	}
}
?>
