<?php

namespace intradesys\api\ebay\trading;
// autogenerated file 22.07.2011 09:27
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'TaxJurisdictionType.php';

/**
 * Sales tax details for zero or more jurisdictions (states,provinces, etc). 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/TaxTableType.html
 *
 */
class TaxTableType extends EbatNs_ComplexType
{
	/**
	 * @var TaxJurisdictionType
	 */
	protected $TaxJurisdiction;

	/**
	 * @return TaxJurisdictionType
	 * @param integer $index 
	 */
	function getTaxJurisdiction($index = null)
	{
		if ($index !== null) {
			return $this->TaxJurisdiction[$index];
		} else {
			return $this->TaxJurisdiction;
		}
	}
	/**
	 * @return void
	 * @param TaxJurisdictionType $value 
	 * @param  $index 
	 */
	function setTaxJurisdiction($value, $index = null)
	{
		if ($index !== null) {
			$this->TaxJurisdiction[$index] = $value;
		} else {
			$this->TaxJurisdiction = $value;
		}
	}
	/**
	 * @return void
	 * @param TaxJurisdictionType $value 
	 */
	function addTaxJurisdiction($value)
	{
		$this->TaxJurisdiction[] = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('TaxTableType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))]))
				self::$_elements[join('', array_slice(explode('\\', __CLASS__), -1))] = array_merge(self::$_elements[join('', array_slice(explode('\\', get_parent_class()), -1))],
				array(
					'TaxJurisdiction' =>
					array(
						'required' => false,
						'type' => 'TaxJurisdictionType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => true,
						'cardinality' => '0..*'
					)
				));
	}
}
?>
